[workspace]
channels = ["conda-forge"]
name = "timewebreversproxy"
platforms = ["linux-64", "win-64"]

version = "0.1.0"


[tasks]
check_src_errors = "pyright src/ --level error"



[dependencies]
python = ">=3.10,<3.11"
pyright = ">=1.1.405,<2"
pytest = ">=8.4.1,<9"
pytest-asyncio = ">=1.1.0,<2"




[pypi-dependencies]
openai=">=1.107.2,<2.0.0"
python-dotenv=">=1.1.1,<2.0.0"
fastapi-proxy-lib=">=0.3.0, <1.0"
pydantic-settings= ">=2.10.1,<3.0.0"
httpx = { version = "*", extras = ["http2"] }


